-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  employee_id character varying NOT NULL UNIQUE,
  phone character varying NOT NULL,
  department character varying,
  position character varying NOT NULL,
  access_level integer DEFAULT 1 CHECK (access_level >= 1 AND access_level <= 10),
  hire_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT admin_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.appointment_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  appointment_id uuid NOT NULL,
  service_id uuid NOT NULL,
  quantity integer DEFAULT 1 CHECK (quantity > 0),
  actual_price numeric NOT NULL CHECK (actual_price >= 0::numeric),
  performed_by uuid,
  service_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointment_services_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_services_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT appointment_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT appointment_services_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.veterinarian_profiles(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  appointment_number character varying NOT NULL UNIQUE,
  pet_id uuid NOT NULL,
  veterinarian_id uuid NOT NULL,
  booked_by uuid NOT NULL,
  appointment_type USER-DEFINED NOT NULL,
  appointment_status USER-DEFINED DEFAULT 'pending'::appointment_status,
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone NOT NULL,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  reason_for_visit text NOT NULL,
  special_instructions text,
  cancellation_reason text,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  is_emergency boolean DEFAULT false,
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp with time zone,
  checked_in_at timestamp with time zone,
  checked_out_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT appointments_veterinarian_id_fkey FOREIGN KEY (veterinarian_id) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT appointments_booked_by_fkey FOREIGN KEY (booked_by) REFERENCES public.users(id),
  CONSTRAINT appointments_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id),
  CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT appointments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action_type USER-DEFINED NOT NULL,
  table_name character varying NOT NULL,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.client_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying NOT NULL CHECK (phone::text ~* '^\+?[1-9]\d{1,14}$'::text),
  alternate_phone character varying,
  address_line1 character varying NOT NULL,
  address_line2 character varying,
  city character varying NOT NULL,
  state character varying NOT NULL,
  zip_code character varying NOT NULL CHECK (zip_code::text ~* '^\d{5}(-\d{4})?$'::text),
  country character varying DEFAULT 'USA'::character varying,
  communication_preference USER-DEFINED DEFAULT 'email'::communication_preference,
  registration_date date DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT client_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.clinic_schedule (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  opening_time time without time zone NOT NULL,
  closing_time time without time zone NOT NULL,
  break_start_time time without time zone,
  break_end_time time without time zone,
  is_emergency_hours boolean DEFAULT false,
  is_closed boolean DEFAULT false,
  effective_from date DEFAULT CURRENT_DATE,
  effective_until date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_schedule_pkey PRIMARY KEY (id)
);
CREATE TABLE public.emergency_contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  contact_name character varying NOT NULL,
  relationship character varying NOT NULL,
  phone character varying NOT NULL,
  alternate_phone character varying,
  email character varying,
  priority_order integer DEFAULT 1 CHECK (priority_order > 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT emergency_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT emergency_contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id)
);
CREATE TABLE public.holiday_closures (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  holiday_name character varying NOT NULL,
  closure_date date NOT NULL,
  is_emergency_available boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT holiday_closures_pkey PRIMARY KEY (id),
  CONSTRAINT holiday_closures_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_profiles(id)
);
CREATE TABLE public.invoice_line_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_id uuid NOT NULL,
  service_id uuid,
  description character varying NOT NULL,
  quantity numeric DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  line_total numeric NOT NULL CHECK (line_total >= 0::numeric),
  is_taxable boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_line_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_line_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_number character varying NOT NULL UNIQUE,
  appointment_id uuid NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  issue_date date DEFAULT CURRENT_DATE,
  due_date date NOT NULL,
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  amount_paid numeric DEFAULT 0 CHECK (amount_paid >= 0::numeric),
  payment_status USER-DEFINED DEFAULT 'unpaid'::payment_status,
  notes text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_profiles(id),
  CONSTRAINT invoices_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.medical_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  record_number character varying NOT NULL UNIQUE,
  appointment_id uuid NOT NULL UNIQUE,
  pet_id uuid NOT NULL,
  veterinarian_id uuid NOT NULL,
  visit_date date NOT NULL,
  chief_complaint text NOT NULL,
  examination_findings text,
  diagnosis text,
  treatment_plan text,
  follow_up_instructions text,
  next_appointment_recommended date,
  record_created_by uuid NOT NULL,
  record_approved_by uuid,
  approved_at timestamp with time zone,
  is_confidential boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT medical_records_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT medical_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT medical_records_veterinarian_id_fkey FOREIGN KEY (veterinarian_id) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT medical_records_record_created_by_fkey FOREIGN KEY (record_created_by) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT medical_records_record_approved_by_fkey FOREIGN KEY (record_approved_by) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT medical_records_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.medical_test_results (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  medical_record_id uuid NOT NULL,
  test_type character varying NOT NULL,
  test_name character varying NOT NULL,
  test_date date NOT NULL,
  ordered_by uuid NOT NULL,
  results text,
  findings text,
  interpretation_notes text,
  file_attachments ARRAY,
  is_abnormal boolean DEFAULT false,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medical_test_results_pkey PRIMARY KEY (id),
  CONSTRAINT medical_test_results_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(id),
  CONSTRAINT medical_test_results_ordered_by_fkey FOREIGN KEY (ordered_by) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT medical_test_results_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.veterinarian_profiles(id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id uuid NOT NULL,
  notification_type USER-DEFINED NOT NULL,
  subject character varying,
  content text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  delivery_status USER-DEFINED DEFAULT 'pending'::notification_status,
  delivery_attempted_at timestamp with time zone,
  delivered_at timestamp with time zone,
  error_message text,
  related_entity_type character varying,
  related_entity_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payment_number character varying NOT NULL UNIQUE,
  invoice_id uuid NOT NULL,
  payment_date date DEFAULT CURRENT_DATE,
  amount_paid numeric NOT NULL CHECK (amount_paid > 0::numeric),
  payment_method USER-DEFINED NOT NULL,
  transaction_reference character varying,
  payment_gateway_response text,
  processed_by uuid NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.admin_profiles(id)
);
CREATE TABLE public.pet_insurance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pet_id uuid NOT NULL,
  provider_name character varying NOT NULL,
  policy_number character varying NOT NULL UNIQUE,
  coverage_details text,
  effective_date date NOT NULL,
  expiration_date date NOT NULL,
  requires_preauth boolean DEFAULT false,
  preauth_phone character varying,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pet_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT pet_insurance_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name character varying NOT NULL,
  species character varying NOT NULL,
  breed character varying,
  date_of_birth date,
  gender USER-DEFINED,
  color character varying,
  weight numeric CHECK (weight > 0::numeric),
  microchip_number character varying UNIQUE,
  is_spayed_neutered boolean DEFAULT false,
  special_needs text,
  behavioral_notes text,
  current_medical_status text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.client_profiles(id),
  CONSTRAINT pets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT pets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT pets_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  medical_record_id uuid NOT NULL,
  medication_name character varying NOT NULL,
  dosage character varying NOT NULL,
  form character varying,
  frequency character varying NOT NULL,
  duration character varying,
  quantity numeric,
  instructions text NOT NULL,
  prescribed_by uuid NOT NULL,
  approved_by uuid,
  dispensed_date date,
  dispensed_by uuid,
  refills_allowed integer DEFAULT 0 CHECK (refills_allowed >= 0),
  is_controlled_substance boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(id),
  CONSTRAINT prescriptions_prescribed_by_fkey FOREIGN KEY (prescribed_by) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT prescriptions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.admin_profiles(id),
  CONSTRAINT prescriptions_dispensed_by_fkey FOREIGN KEY (dispensed_by) REFERENCES public.users(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  service_name character varying NOT NULL,
  service_category character varying NOT NULL,
  description text,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  duration_minutes integer CHECK (duration_minutes > 0),
  requires_specialist boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT services_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  role USER-DEFINED NOT NULL,
  account_status USER-DEFINED DEFAULT 'active'::account_status,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.vaccination_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pet_id uuid NOT NULL,
  medical_record_id uuid,
  vaccine_name character varying NOT NULL,
  vaccine_type character varying NOT NULL,
  administered_date date NOT NULL,
  administered_by uuid NOT NULL,
  next_due_date date,
  batch_number character varying,
  lot_number character varying,
  manufacturer character varying,
  expiration_date date,
  injection_site character varying,
  side_effects_noted text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vaccination_records_pkey PRIMARY KEY (id),
  CONSTRAINT vaccination_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT vaccination_records_medical_record_id_fkey FOREIGN KEY (medical_record_id) REFERENCES public.medical_records(id),
  CONSTRAINT vaccination_records_administered_by_fkey FOREIGN KEY (administered_by) REFERENCES public.veterinarian_profiles(id)
);
CREATE TABLE public.veterinarian_availability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  veterinarian_id uuid NOT NULL,
  availability_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  unavailability_reason character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT veterinarian_availability_pkey PRIMARY KEY (id),
  CONSTRAINT veterinarian_availability_veterinarian_id_fkey FOREIGN KEY (veterinarian_id) REFERENCES public.veterinarian_profiles(id),
  CONSTRAINT veterinarian_availability_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.veterinarian_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  license_number character varying NOT NULL UNIQUE,
  phone character varying NOT NULL,
  specializations ARRAY,
  certifications ARRAY,
  years_of_experience integer CHECK (years_of_experience >= 0),
  biography text,
  consultation_fee numeric CHECK (consultation_fee >= 0::numeric),
  employment_status USER-DEFINED DEFAULT 'full_time'::employment_status,
  hire_date date NOT NULL,
  termination_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT veterinarian_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT veterinarian_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);